name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.1.4
  - pytest=6.2.2
  - scipy=1.5.2
  - hydra-core=1.0.6
  - pip=20.3.3
  - pip:
      - wandb==0.13.2
      - hydra-joblib-launcher==1.1.2