name: airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=1.29.0
  - git=2.30.2
  - ipython=8.5.0
  - notebook=6.4.12
  - jupyterlab=3.4.0
  - cookiecutter=1.7.2
  - hydra-core=1.2.0
  - matplotlib=3.5.3
  - pandas=1.4.4
  - pip=22.2.2
  - pip:
      - wandb==0.13.2
