name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - mlflow=1.29.0
  - scikit-learn=0.24.1
  - pip=20.3.3
  - pip:
      - wandb==0.13.2
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
