name: train
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - pip=20.3.3
  - pip:
      - wandb==0.13.2
